// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoteManager.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NoteManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260606135152_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NoteManager.Models.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Note", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f7c2d91-8b4e-4a6f-9c12-7d5e8a1b2c34"),
                            Content = "Welcome to the notes app.",
                            CreatedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Note 1"
                        },
                        new
                        {
                            Id = new Guid("a92d6f10-3b7a-4e85-b1c9-2f4d7a8e6c11"),
                            Content = "How are you doing today?",
                            CreatedAt = new DateTime(2026, 1, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Note 2"
                        },
                        new
                        {
                            Id = new Guid("6c1e9a44-5f2b-4d73-8a90-1e2f3b4c5d66"),
                            Content = "Remember to review the API endpoints.",
                            CreatedAt = new DateTime(2026, 1, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Note 3"
                        },
                        new
                        {
                            Id = new Guid("f4b82c17-9d6e-4f21-a7b3-8c0d1e2f9a55"),
                            Content = "Buy groceries after classes.",
                            CreatedAt = new DateTime(2026, 1, 4, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Note 4"
                        },
                        new
                        {
                            Id = new Guid("19a7d3e8-2c4f-4b61-96ad-5e7f8c1d2b90"),
                            Content = "Read about dependency injection in ASP.NET Core.",
                            CreatedAt = new DateTime(2026, 1, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Note 5"
                        },
                        new
                        {
                            Id = new Guid("c8f14b62-7a3d-4e9c-b205-6d1f2a3b4c88"),
                            Content = "Prepare the database migration for the project.",
                            CreatedAt = new DateTime(2026, 1, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Note 6"
                        },
                        new
                        {
                            Id = new Guid("72e5a9c1-4d8f-4b30-8e17-9a2c6f3d1b77"),
                            Content = "Finish the controller methods and test them.",
                            CreatedAt = new DateTime(2026, 1, 7, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Note 7"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
